### PR TITLE
add support for custom sorting of breadcrumbsItems

### PR DESCRIPTION
**Pull request by zmeecer**
update docs

### CODE REVIEW

**Comment by oklas** [comment]
Use `Object.values` as required [here](https://github.com/oklas/react-breadcrumbs-dynamic/issues/19#issuecomment-376293839) i.e.:
* make sorted data `array of values` intead of `array of keys` for user func

Not need to create additional complicated data structure or arrays like from `Object.entries`.
Use  `(a, b) => a[breadcrumbsBearingKey].length - b[breadcrumbsBearingKey].length`
for default sorting. (Path already is in prop `to`).
And use some like this `(a, b) => a.wight - b.weight` for custom sorting.

**Comment by oklas** [comment]
Also please make doc shortly. Two sentence in existed section is enough, just about that function which used as sorting criteria of array of item props.

**Comment by oklas** [comment]
Tests fails on some environment or browsers. Let's switch from `Object.values` to `keys(obj).map(k=>obj[k])` idiom.

**Comment by zmeecer** [comment]
I was not sure about adding `babel-polyfill` or replacing with Object.keys or smth else
BTW, fixed

**Comment by oklas** [comment]
You have comitted from different git authoring configuration. Git does not recognize commits as maded by you. Please configure your git with same email and user name as your account. Replace commits authoring information and create new pr.

**Comment by oklas** [comment]
If it is ok for you - say to me and it will be merged as is .

**Comment by zmeecer** [comment]
changed, but did not understand how to remove the second author in commits

**Comment by oklas** [comment]
when you reset muster push it

**Comment by oklas** [comment]
do pr if problem solved

**Comment by zmeecer** [comment]
oh, sorry, have completely forgotten about `reset`
fixed, loot at #21

**Pull request merged**
