### PR TITLE
adds hideIfEmpty prop, small props refactoring

### PR DESCRIPTION
**Pull request by FriOne**

### CODE REVIEW

**Comment by oklas** [comment]
Please remove `package-lock.json` due to `yarn.lock` is used. Update README.md with remark after table row `compare` to let users knows about cool feature. Also may be add test that container exists if no `hideIfEmpty` is specified to be sure with backward compatibility.

**Comment by FriOne** [comment]
Could you give me direction on how to make tests? I don't understand how you organize files.

**Comment by oklas** [comment]
The file `index.spec-set`, where you added the test is like reusable library, it contain set of tests, which applied to different implementations. Also there some additional tests which do not uses that spec set. You added test in correct place.

**Comment by FriOne** [comment]
@oklas yeah, but you have several TestApp that is not imported explicitly. And I need new TestApp with empty breadcrumbs. So where should I put it? Or I need  add props to some of your TestApp's?

**Comment by oklas** [comment]
yes, add props to some of TestApp's

**Comment by FriOne** [comment]
Sorry, waste too much time on a such easy thing, even I don't really necessary to fix it.
If you want you can use my code to make change, but it would be easier to make it by yourself.
You need to make some refactoring and clean up the code I think.

**Comment by oklas** [comment]
Thank you. Please update commit by removing `.idea` folder. I will look at this.

**Comment by oklas** [comment]
Oh, do nothing, commit f6efe1567304ddc1b5c0bb03a99cf586a4989727 still available and looks good, i will continue from it.

**Comment by oklas** [comment]
Hi @FriOne. System does not recognize your commits as maded by you. Emails mismatch. The commits which you provided authored with different email than your acount. Could you please reassign your email in your commits in branch [hide-if-empty](https://github.com/oklas/react-breadcrumbs-dynamic/commits/hide-if-empty). Or may be chage your account email will help. You can see that it is ok when your photo will be on your commits. You can just push in your fork repo. Ready to release. Looking forward your activity about authoring.

**Pull request closed without merging**
